// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cities.proto

public final class Cities {
  private Cities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:City)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 zip_code = 2;</code>
     * @return The zipCode.
     */
    int getZipCode();

    /**
     * <code>string country_name = 3;</code>
     * @return The countryName.
     */
    java.lang.String getCountryName();
    /**
     * <code>string country_name = 3;</code>
     * @return The bytes for countryName.
     */
    com.google.protobuf.ByteString
        getCountryNameBytes();
  }
  /**
   * Protobuf type {@code City}
   */
  public static final class City extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:City)
      CityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use City.newBuilder() to construct.
    private City(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private City() {
      name_ = "";
      countryName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new City();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private City(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              zipCode_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              countryName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cities.internal_static_City_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cities.internal_static_City_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cities.City.class, Cities.City.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIP_CODE_FIELD_NUMBER = 2;
    private int zipCode_;
    /**
     * <code>uint32 zip_code = 2;</code>
     * @return The zipCode.
     */
    @java.lang.Override
    public int getZipCode() {
      return zipCode_;
    }

    public static final int COUNTRY_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object countryName_;
    /**
     * <code>string country_name = 3;</code>
     * @return The countryName.
     */
    @java.lang.Override
    public java.lang.String getCountryName() {
      java.lang.Object ref = countryName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryName_ = s;
        return s;
      }
    }
    /**
     * <code>string country_name = 3;</code>
     * @return The bytes for countryName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryNameBytes() {
      java.lang.Object ref = countryName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (zipCode_ != 0) {
        output.writeUInt32(2, zipCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, countryName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (zipCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, zipCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, countryName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Cities.City)) {
        return super.equals(obj);
      }
      Cities.City other = (Cities.City) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getZipCode()
          != other.getZipCode()) return false;
      if (!getCountryName()
          .equals(other.getCountryName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ZIP_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getZipCode();
      hash = (37 * hash) + COUNTRY_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCountryName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Cities.City parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.City parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.City parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.City parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.City parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.City parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.City parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cities.City parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cities.City parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Cities.City parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cities.City parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cities.City parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Cities.City prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code City}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:City)
        Cities.CityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cities.internal_static_City_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cities.internal_static_City_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cities.City.class, Cities.City.Builder.class);
      }

      // Construct using Cities.City.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        zipCode_ = 0;

        countryName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cities.internal_static_City_descriptor;
      }

      @java.lang.Override
      public Cities.City getDefaultInstanceForType() {
        return Cities.City.getDefaultInstance();
      }

      @java.lang.Override
      public Cities.City build() {
        Cities.City result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Cities.City buildPartial() {
        Cities.City result = new Cities.City(this);
        result.name_ = name_;
        result.zipCode_ = zipCode_;
        result.countryName_ = countryName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cities.City) {
          return mergeFrom((Cities.City)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cities.City other) {
        if (other == Cities.City.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getZipCode() != 0) {
          setZipCode(other.getZipCode());
        }
        if (!other.getCountryName().isEmpty()) {
          countryName_ = other.countryName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cities.City parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cities.City) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int zipCode_ ;
      /**
       * <code>uint32 zip_code = 2;</code>
       * @return The zipCode.
       */
      @java.lang.Override
      public int getZipCode() {
        return zipCode_;
      }
      /**
       * <code>uint32 zip_code = 2;</code>
       * @param value The zipCode to set.
       * @return This builder for chaining.
       */
      public Builder setZipCode(int value) {
        
        zipCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 zip_code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearZipCode() {
        
        zipCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object countryName_ = "";
      /**
       * <code>string country_name = 3;</code>
       * @return The countryName.
       */
      public java.lang.String getCountryName() {
        java.lang.Object ref = countryName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country_name = 3;</code>
       * @return The bytes for countryName.
       */
      public com.google.protobuf.ByteString
          getCountryNameBytes() {
        java.lang.Object ref = countryName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country_name = 3;</code>
       * @param value The countryName to set.
       * @return This builder for chaining.
       */
      public Builder setCountryName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        countryName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string country_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryName() {
        
        countryName_ = getDefaultInstance().getCountryName();
        onChanged();
        return this;
      }
      /**
       * <code>string country_name = 3;</code>
       * @param value The bytes for countryName to set.
       * @return This builder for chaining.
       */
      public Builder setCountryNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        countryName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:City)
    }

    // @@protoc_insertion_point(class_scope:City)
    private static final Cities.City DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Cities.City();
    }

    public static Cities.City getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<City>
        PARSER = new com.google.protobuf.AbstractParser<City>() {
      @java.lang.Override
      public City parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new City(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<City> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<City> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Cities.City getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StreetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Street)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string street_name = 4;</code>
     * @return The streetName.
     */
    java.lang.String getStreetName();
    /**
     * <code>string street_name = 4;</code>
     * @return The bytes for streetName.
     */
    com.google.protobuf.ByteString
        getStreetNameBytes();

    /**
     * <code>.City city = 5;</code>
     * @return Whether the city field is set.
     */
    boolean hasCity();
    /**
     * <code>.City city = 5;</code>
     * @return The city.
     */
    Cities.City getCity();
    /**
     * <code>.City city = 5;</code>
     */
    Cities.CityOrBuilder getCityOrBuilder();
  }
  /**
   * Protobuf type {@code Street}
   */
  public static final class Street extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Street)
      StreetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Street.newBuilder() to construct.
    private Street(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Street() {
      streetName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Street();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Street(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              streetName_ = s;
              break;
            }
            case 42: {
              Cities.City.Builder subBuilder = null;
              if (city_ != null) {
                subBuilder = city_.toBuilder();
              }
              city_ = input.readMessage(Cities.City.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(city_);
                city_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cities.internal_static_Street_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cities.internal_static_Street_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cities.Street.class, Cities.Street.Builder.class);
    }

    public static final int STREET_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object streetName_;
    /**
     * <code>string street_name = 4;</code>
     * @return The streetName.
     */
    @java.lang.Override
    public java.lang.String getStreetName() {
      java.lang.Object ref = streetName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetName_ = s;
        return s;
      }
    }
    /**
     * <code>string street_name = 4;</code>
     * @return The bytes for streetName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetNameBytes() {
      java.lang.Object ref = streetName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 5;
    private Cities.City city_;
    /**
     * <code>.City city = 5;</code>
     * @return Whether the city field is set.
     */
    @java.lang.Override
    public boolean hasCity() {
      return city_ != null;
    }
    /**
     * <code>.City city = 5;</code>
     * @return The city.
     */
    @java.lang.Override
    public Cities.City getCity() {
      return city_ == null ? Cities.City.getDefaultInstance() : city_;
    }
    /**
     * <code>.City city = 5;</code>
     */
    @java.lang.Override
    public Cities.CityOrBuilder getCityOrBuilder() {
      return getCity();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, streetName_);
      }
      if (city_ != null) {
        output.writeMessage(5, getCity());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streetName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, streetName_);
      }
      if (city_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCity());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Cities.Street)) {
        return super.equals(obj);
      }
      Cities.Street other = (Cities.Street) obj;

      if (!getStreetName()
          .equals(other.getStreetName())) return false;
      if (hasCity() != other.hasCity()) return false;
      if (hasCity()) {
        if (!getCity()
            .equals(other.getCity())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREET_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getStreetName().hashCode();
      if (hasCity()) {
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Cities.Street parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.Street parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.Street parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.Street parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.Street parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.Street parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.Street parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cities.Street parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cities.Street parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Cities.Street parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cities.Street parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cities.Street parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Cities.Street prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Street}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Street)
        Cities.StreetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cities.internal_static_Street_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cities.internal_static_Street_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cities.Street.class, Cities.Street.Builder.class);
      }

      // Construct using Cities.Street.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        streetName_ = "";

        if (cityBuilder_ == null) {
          city_ = null;
        } else {
          city_ = null;
          cityBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cities.internal_static_Street_descriptor;
      }

      @java.lang.Override
      public Cities.Street getDefaultInstanceForType() {
        return Cities.Street.getDefaultInstance();
      }

      @java.lang.Override
      public Cities.Street build() {
        Cities.Street result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Cities.Street buildPartial() {
        Cities.Street result = new Cities.Street(this);
        result.streetName_ = streetName_;
        if (cityBuilder_ == null) {
          result.city_ = city_;
        } else {
          result.city_ = cityBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cities.Street) {
          return mergeFrom((Cities.Street)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cities.Street other) {
        if (other == Cities.Street.getDefaultInstance()) return this;
        if (!other.getStreetName().isEmpty()) {
          streetName_ = other.streetName_;
          onChanged();
        }
        if (other.hasCity()) {
          mergeCity(other.getCity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cities.Street parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cities.Street) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object streetName_ = "";
      /**
       * <code>string street_name = 4;</code>
       * @return The streetName.
       */
      public java.lang.String getStreetName() {
        java.lang.Object ref = streetName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streetName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string street_name = 4;</code>
       * @return The bytes for streetName.
       */
      public com.google.protobuf.ByteString
          getStreetNameBytes() {
        java.lang.Object ref = streetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string street_name = 4;</code>
       * @param value The streetName to set.
       * @return This builder for chaining.
       */
      public Builder setStreetName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        streetName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string street_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreetName() {
        
        streetName_ = getDefaultInstance().getStreetName();
        onChanged();
        return this;
      }
      /**
       * <code>string street_name = 4;</code>
       * @param value The bytes for streetName to set.
       * @return This builder for chaining.
       */
      public Builder setStreetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        streetName_ = value;
        onChanged();
        return this;
      }

      private Cities.City city_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Cities.City, Cities.City.Builder, Cities.CityOrBuilder> cityBuilder_;
      /**
       * <code>.City city = 5;</code>
       * @return Whether the city field is set.
       */
      public boolean hasCity() {
        return cityBuilder_ != null || city_ != null;
      }
      /**
       * <code>.City city = 5;</code>
       * @return The city.
       */
      public Cities.City getCity() {
        if (cityBuilder_ == null) {
          return city_ == null ? Cities.City.getDefaultInstance() : city_;
        } else {
          return cityBuilder_.getMessage();
        }
      }
      /**
       * <code>.City city = 5;</code>
       */
      public Builder setCity(Cities.City value) {
        if (cityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          city_ = value;
          onChanged();
        } else {
          cityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.City city = 5;</code>
       */
      public Builder setCity(
          Cities.City.Builder builderForValue) {
        if (cityBuilder_ == null) {
          city_ = builderForValue.build();
          onChanged();
        } else {
          cityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.City city = 5;</code>
       */
      public Builder mergeCity(Cities.City value) {
        if (cityBuilder_ == null) {
          if (city_ != null) {
            city_ =
              Cities.City.newBuilder(city_).mergeFrom(value).buildPartial();
          } else {
            city_ = value;
          }
          onChanged();
        } else {
          cityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.City city = 5;</code>
       */
      public Builder clearCity() {
        if (cityBuilder_ == null) {
          city_ = null;
          onChanged();
        } else {
          city_ = null;
          cityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.City city = 5;</code>
       */
      public Cities.City.Builder getCityBuilder() {
        
        onChanged();
        return getCityFieldBuilder().getBuilder();
      }
      /**
       * <code>.City city = 5;</code>
       */
      public Cities.CityOrBuilder getCityOrBuilder() {
        if (cityBuilder_ != null) {
          return cityBuilder_.getMessageOrBuilder();
        } else {
          return city_ == null ?
              Cities.City.getDefaultInstance() : city_;
        }
      }
      /**
       * <code>.City city = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Cities.City, Cities.City.Builder, Cities.CityOrBuilder> 
          getCityFieldBuilder() {
        if (cityBuilder_ == null) {
          cityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Cities.City, Cities.City.Builder, Cities.CityOrBuilder>(
                  getCity(),
                  getParentForChildren(),
                  isClean());
          city_ = null;
        }
        return cityBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Street)
    }

    // @@protoc_insertion_point(class_scope:Street)
    private static final Cities.Street DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Cities.Street();
    }

    public static Cities.Street getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Street>
        PARSER = new com.google.protobuf.AbstractParser<Street>() {
      @java.lang.Override
      public Street parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Street(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Street> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Street> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Cities.Street getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuildingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Building)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string building_name = 6;</code>
     * @return The buildingName.
     */
    java.lang.String getBuildingName();
    /**
     * <code>string building_name = 6;</code>
     * @return The bytes for buildingName.
     */
    com.google.protobuf.ByteString
        getBuildingNameBytes();

    /**
     * <code>uint32 building_number = 7;</code>
     * @return The buildingNumber.
     */
    int getBuildingNumber();

    /**
     * <code>.Street street = 8;</code>
     * @return Whether the street field is set.
     */
    boolean hasStreet();
    /**
     * <code>.Street street = 8;</code>
     * @return The street.
     */
    Cities.Street getStreet();
    /**
     * <code>.Street street = 8;</code>
     */
    Cities.StreetOrBuilder getStreetOrBuilder();
  }
  /**
   * Protobuf type {@code Building}
   */
  public static final class Building extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Building)
      BuildingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Building.newBuilder() to construct.
    private Building(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Building() {
      buildingName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Building();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Building(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              buildingName_ = s;
              break;
            }
            case 56: {

              buildingNumber_ = input.readUInt32();
              break;
            }
            case 66: {
              Cities.Street.Builder subBuilder = null;
              if (street_ != null) {
                subBuilder = street_.toBuilder();
              }
              street_ = input.readMessage(Cities.Street.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(street_);
                street_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cities.internal_static_Building_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cities.internal_static_Building_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cities.Building.class, Cities.Building.Builder.class);
    }

    public static final int BUILDING_NAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object buildingName_;
    /**
     * <code>string building_name = 6;</code>
     * @return The buildingName.
     */
    @java.lang.Override
    public java.lang.String getBuildingName() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingName_ = s;
        return s;
      }
    }
    /**
     * <code>string building_name = 6;</code>
     * @return The bytes for buildingName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildingNameBytes() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILDING_NUMBER_FIELD_NUMBER = 7;
    private int buildingNumber_;
    /**
     * <code>uint32 building_number = 7;</code>
     * @return The buildingNumber.
     */
    @java.lang.Override
    public int getBuildingNumber() {
      return buildingNumber_;
    }

    public static final int STREET_FIELD_NUMBER = 8;
    private Cities.Street street_;
    /**
     * <code>.Street street = 8;</code>
     * @return Whether the street field is set.
     */
    @java.lang.Override
    public boolean hasStreet() {
      return street_ != null;
    }
    /**
     * <code>.Street street = 8;</code>
     * @return The street.
     */
    @java.lang.Override
    public Cities.Street getStreet() {
      return street_ == null ? Cities.Street.getDefaultInstance() : street_;
    }
    /**
     * <code>.Street street = 8;</code>
     */
    @java.lang.Override
    public Cities.StreetOrBuilder getStreetOrBuilder() {
      return getStreet();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buildingName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, buildingName_);
      }
      if (buildingNumber_ != 0) {
        output.writeUInt32(7, buildingNumber_);
      }
      if (street_ != null) {
        output.writeMessage(8, getStreet());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(buildingName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, buildingName_);
      }
      if (buildingNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, buildingNumber_);
      }
      if (street_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getStreet());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Cities.Building)) {
        return super.equals(obj);
      }
      Cities.Building other = (Cities.Building) obj;

      if (!getBuildingName()
          .equals(other.getBuildingName())) return false;
      if (getBuildingNumber()
          != other.getBuildingNumber()) return false;
      if (hasStreet() != other.hasStreet()) return false;
      if (hasStreet()) {
        if (!getStreet()
            .equals(other.getStreet())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDING_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingName().hashCode();
      hash = (37 * hash) + BUILDING_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingNumber();
      if (hasStreet()) {
        hash = (37 * hash) + STREET_FIELD_NUMBER;
        hash = (53 * hash) + getStreet().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Cities.Building parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.Building parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.Building parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.Building parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.Building parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cities.Building parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cities.Building parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cities.Building parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cities.Building parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Cities.Building parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cities.Building parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cities.Building parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Cities.Building prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Building}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Building)
        Cities.BuildingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cities.internal_static_Building_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cities.internal_static_Building_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cities.Building.class, Cities.Building.Builder.class);
      }

      // Construct using Cities.Building.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        buildingName_ = "";

        buildingNumber_ = 0;

        if (streetBuilder_ == null) {
          street_ = null;
        } else {
          street_ = null;
          streetBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cities.internal_static_Building_descriptor;
      }

      @java.lang.Override
      public Cities.Building getDefaultInstanceForType() {
        return Cities.Building.getDefaultInstance();
      }

      @java.lang.Override
      public Cities.Building build() {
        Cities.Building result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Cities.Building buildPartial() {
        Cities.Building result = new Cities.Building(this);
        result.buildingName_ = buildingName_;
        result.buildingNumber_ = buildingNumber_;
        if (streetBuilder_ == null) {
          result.street_ = street_;
        } else {
          result.street_ = streetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cities.Building) {
          return mergeFrom((Cities.Building)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cities.Building other) {
        if (other == Cities.Building.getDefaultInstance()) return this;
        if (!other.getBuildingName().isEmpty()) {
          buildingName_ = other.buildingName_;
          onChanged();
        }
        if (other.getBuildingNumber() != 0) {
          setBuildingNumber(other.getBuildingNumber());
        }
        if (other.hasStreet()) {
          mergeStreet(other.getStreet());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cities.Building parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cities.Building) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object buildingName_ = "";
      /**
       * <code>string building_name = 6;</code>
       * @return The buildingName.
       */
      public java.lang.String getBuildingName() {
        java.lang.Object ref = buildingName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string building_name = 6;</code>
       * @return The bytes for buildingName.
       */
      public com.google.protobuf.ByteString
          getBuildingNameBytes() {
        java.lang.Object ref = buildingName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string building_name = 6;</code>
       * @param value The buildingName to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buildingName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string building_name = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingName() {
        
        buildingName_ = getDefaultInstance().getBuildingName();
        onChanged();
        return this;
      }
      /**
       * <code>string building_name = 6;</code>
       * @param value The bytes for buildingName to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buildingName_ = value;
        onChanged();
        return this;
      }

      private int buildingNumber_ ;
      /**
       * <code>uint32 building_number = 7;</code>
       * @return The buildingNumber.
       */
      @java.lang.Override
      public int getBuildingNumber() {
        return buildingNumber_;
      }
      /**
       * <code>uint32 building_number = 7;</code>
       * @param value The buildingNumber to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingNumber(int value) {
        
        buildingNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 building_number = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingNumber() {
        
        buildingNumber_ = 0;
        onChanged();
        return this;
      }

      private Cities.Street street_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Cities.Street, Cities.Street.Builder, Cities.StreetOrBuilder> streetBuilder_;
      /**
       * <code>.Street street = 8;</code>
       * @return Whether the street field is set.
       */
      public boolean hasStreet() {
        return streetBuilder_ != null || street_ != null;
      }
      /**
       * <code>.Street street = 8;</code>
       * @return The street.
       */
      public Cities.Street getStreet() {
        if (streetBuilder_ == null) {
          return street_ == null ? Cities.Street.getDefaultInstance() : street_;
        } else {
          return streetBuilder_.getMessage();
        }
      }
      /**
       * <code>.Street street = 8;</code>
       */
      public Builder setStreet(Cities.Street value) {
        if (streetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          street_ = value;
          onChanged();
        } else {
          streetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Street street = 8;</code>
       */
      public Builder setStreet(
          Cities.Street.Builder builderForValue) {
        if (streetBuilder_ == null) {
          street_ = builderForValue.build();
          onChanged();
        } else {
          streetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Street street = 8;</code>
       */
      public Builder mergeStreet(Cities.Street value) {
        if (streetBuilder_ == null) {
          if (street_ != null) {
            street_ =
              Cities.Street.newBuilder(street_).mergeFrom(value).buildPartial();
          } else {
            street_ = value;
          }
          onChanged();
        } else {
          streetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Street street = 8;</code>
       */
      public Builder clearStreet() {
        if (streetBuilder_ == null) {
          street_ = null;
          onChanged();
        } else {
          street_ = null;
          streetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Street street = 8;</code>
       */
      public Cities.Street.Builder getStreetBuilder() {
        
        onChanged();
        return getStreetFieldBuilder().getBuilder();
      }
      /**
       * <code>.Street street = 8;</code>
       */
      public Cities.StreetOrBuilder getStreetOrBuilder() {
        if (streetBuilder_ != null) {
          return streetBuilder_.getMessageOrBuilder();
        } else {
          return street_ == null ?
              Cities.Street.getDefaultInstance() : street_;
        }
      }
      /**
       * <code>.Street street = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Cities.Street, Cities.Street.Builder, Cities.StreetOrBuilder> 
          getStreetFieldBuilder() {
        if (streetBuilder_ == null) {
          streetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Cities.Street, Cities.Street.Builder, Cities.StreetOrBuilder>(
                  getStreet(),
                  getParentForChildren(),
                  isClean());
          street_ = null;
        }
        return streetBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Building)
    }

    // @@protoc_insertion_point(class_scope:Building)
    private static final Cities.Building DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Cities.Building();
    }

    public static Cities.Building getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Building>
        PARSER = new com.google.protobuf.AbstractParser<Building>() {
      @java.lang.Override
      public Building parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Building(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Building> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Building> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Cities.Building getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_City_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_City_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Street_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Street_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Building_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Building_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014cities.proto\"<\n\004City\022\014\n\004name\030\001 \001(\t\022\020\n\010" +
      "zip_code\030\002 \001(\r\022\024\n\014country_name\030\003 \001(\t\"2\n\006" +
      "Street\022\023\n\013street_name\030\004 \001(\t\022\023\n\004city\030\005 \001(" +
      "\0132\005.City\"S\n\010Building\022\025\n\rbuilding_name\030\006 " +
      "\001(\t\022\027\n\017building_number\030\007 \001(\r\022\027\n\006street\030\010" +
      " \001(\0132\007.Streetb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_City_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_City_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_City_descriptor,
        new java.lang.String[] { "Name", "ZipCode", "CountryName", });
    internal_static_Street_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Street_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Street_descriptor,
        new java.lang.String[] { "StreetName", "City", });
    internal_static_Building_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Building_descriptor,
        new java.lang.String[] { "BuildingName", "BuildingNumber", "Street", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
